name: DEV - CONTINUOUS INTEGRATIONS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integrations:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node 10 setup
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 10
      - name: install dependencies
        run: npm ci
      - name: lint standard
        run: npm run lint:fix
      - name: integration tests
        run: npm run cy:run
        env: 
          CYPRESS_APP_URL: "https://serverest.dev"
          CYPRESS_EMAIL: "fulano@qa.com"
          CYPRESS_PASSWORD: "teste"