name: DEV - CONTINUOUS INTEGRATIONS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integrations:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: cypress run tests
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_APP_URL: 'https://serverest.dev'
          CYPRESS_EMAIL:  ${{ secrets.EMAIL }}
          CYPRESS_PASSWORD:  ${{ secrets.PASSWORD }}